### ISSUE TITLE
BlockingIOError when importing wrf-python

### ISSUE THREAD

**Issue by amt1204** [NCAR/wrf-python#100]
Recently, when I try to import the wrf-python module within a script, I get a BlockingIOError. This error does not occur when I import wrf-python in interactive mode. The version of Python that I am using is 3.8.0a3, and the version of wrf-python that I am using is 1.3.1. I am using a Cygwin emulator. Below is the readout of the error, with some information redacted.

>    0 [main] python3.8m 765 child_info_fork::abort: address space needed by 'interpnd.cpython-38m-x86_64-cygwin.dll' (0x1040000) is already occupied
> Traceback (most recent call last):
>   File "REDACTED.py", line 12, in <module>
>     from REDACTED import REDACTED
>   File "REDACTED", line 13, in <module>
>     import wrf
>   File "/usr/lib/python3.8/site-packages/wrf/__init__.py", line 16, in <module>
>     from . import api
>   File "/usr/lib/python3.8/site-packages/wrf/api.py", line 1, in <module>
>     from .config import (xarray_enabled, disable_xarray, enable_xarray,
>   File "/usr/lib/python3.8/site-packages/wrf/config.py", line 44, in <module>
>     _init_local()
>   File "/usr/lib/python3.8/site-packages/wrf/config.py", line 28, in _init_local
>     from cartopy import crs
>   File "/usr/lib/python3.8/site-packages/Cartopy-0.17.1.dev172_-py3.8-cygwin-3.0.7-x86_64.egg/cartopy/__init__.py", line 95, in <module>
>     import cartopy.crs
>   File "/usr/lib/python3.8/site-packages/Cartopy-0.17.1.dev172_-py3.8-cygwin-3.0.7-x86_64.egg/cartopy/crs.py", line 32, in <module>
>     import shapely.geometry as sgeom
>   File "/usr/lib/python3.8/site-packages/Shapely-1.7a2-py3.8.egg/shapely/geometry/__init__.py", line 4, in <module>
>     from .base import CAP_STYLE, JOIN_STYLE
>   File "/usr/lib/python3.8/site-packages/Shapely-1.7a2-py3.8.egg/shapely/geometry/base.py", line 18, in <module>
>     from shapely.coords import CoordinateSequence
>   File "/usr/lib/python3.8/site-packages/Shapely-1.7a2-py3.8.egg/shapely/coords.py", line 8, in <module>
>     from shapely.geos import lgeos
>   File "/usr/lib/python3.8/site-packages/Shapely-1.7a2-py3.8.egg/shapely/geos.py", line 171, in <module>
>     _lgeos = load_dll('geos_c', fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
>   File "/usr/lib/python3.8/site-packages/Shapely-1.7a2-py3.8.egg/shapely/geos.py", line 34, in load_dll
>     lib = find_library(libname)
>   File "/usr/lib/python3.8/ctypes/util.py", line 100, in find_library
>     f = os.popen(cmd)
>   File "/usr/lib/python3.8/os.py", line 980, in popen
>     proc = subprocess.Popen(cmd,
>   File "/usr/lib/python3.8/subprocess.py", line 830, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.8/subprocess.py", line 1583, in _execute_child
>     self.pid = _posixsubprocess.fork_exec(
> BlockingIOError: [Errno 11] Resource temporarily unavailable

**Comment by amt1204** [comment]
It turns out that this was more of an issue with Cywin than with the module. Sorry for the added issue. For reference, the solution was to use `rebaseall -v`
