### ISSUE TITLE
Converting proj information from WrfProj

### ISSUE THREAD

**Issue by pgamez** [NCAR/wrf-python#127]
This code exports the projection in WRF file to **proj4** and **CF** formats:

```python
#!/usr/bin/env python3

from netCDF4 import Dataset
import wrf


filename = 'wrfout_d03_2020-03-19_12:00:00'

with Dataset(filename) as wrfin:
    proj_params = wrf.get_proj_params(wrfin)

proj = wrf.getproj(**proj_params)

print(proj.proj4())
print(proj.cf())
```
The output is:

```
./test.py
+proj=merc +units=meters +a=6370000.0 +b=6370000.0 +lon_0=-74.9000015258789 +lat_ts=4.300000190734863 +nadgrids=@null
{'grid_mapping_name': 'mercator', 'longitude_of_projection_origin': -74.9, 'standard_parallel': 4.3}
```

Two comments:

1. The CF format (unlike the proj4) is lacking the information about the ellipsoid. I think it should be added, for instance:
```python
cf = proj.cf()
cf.update({'earth_radius': wrf.constants.Constants.WRF_EARTH_RADIUS})
```
2. Regarding the proj4 format, I think that the parameter `+units=meters` is actually not supported by the proj4 library. Instead, a value of `+meters=m` should be used. This is the complete list of available map units by proj4:
```python
In [1]: import pyproj as pj

In [2]: pj.get_units_map()
Out[2]: 
{'km': Unit(id='km', to_meter='1000', name='Kilometer', factor=1000.0),
 'm': Unit(id='m', to_meter='1', name='Meter', factor=1.0),
 'dm': Unit(id='dm', to_meter='1/10', name='Decimeter', factor=0.1),
 'cm': Unit(id='cm', to_meter='1/100', name='Centimeter', factor=0.01),
 'mm': Unit(id='mm', to_meter='1/1000', name='Millimeter', factor=0.001),
 'kmi': Unit(id='kmi', to_meter='1852', name='International Nautical Mile', factor=1852.0),
 'in': Unit(id='in', to_meter='0.0254', name='International Inch', factor=0.0254),
 'ft': Unit(id='ft', to_meter='0.3048', name='International Foot', factor=0.3048),
 'yd': Unit(id='yd', to_meter='0.9144', name='International Yard', factor=0.9144),
 'mi': Unit(id='mi', to_meter='1609.344', name='International Statute Mile', factor=1609.344),
 'fath': Unit(id='fath', to_meter='1.8288', name='International Fathom', factor=1.8288),
 'ch': Unit(id='ch', to_meter='20.1168', name='International Chain', factor=20.1168),
 'link': Unit(id='link', to_meter='0.201168', name='International Link', factor=0.201168),
 'us-in': Unit(id='us-in', to_meter='1/39.37', name="U.S. Surveyor's Inch", factor=0.0254000508001016),
 'us-ft': Unit(id='us-ft', to_meter='0.304800609601219', name="U.S. Surveyor's Foot", factor=0.3048006096012192),
 'us-yd': Unit(id='us-yd', to_meter='0.914401828803658', name="U.S. Surveyor's Yard", factor=0.9144018288036576),
 'us-ch': Unit(id='us-ch', to_meter='20.11684023368047', name="U.S. Surveyor's Chain", factor=20.116840233680467),
 'us-mi': Unit(id='us-mi', to_meter='1609.347218694437', name="U.S. Surveyor's Statute Mile", factor=1609.3472186944373),
 'ind-yd': Unit(id='ind-yd', to_meter='0.91439523', name='Indian Yard', factor=0.91439523),
 'ind-ft': Unit(id='ind-ft', to_meter='0.30479841', name='Indian Foot', factor=0.30479841),
 'ind-ch': Unit(id='ind-ch', to_meter='20.11669506', name='Indian Chain', factor=20.11669506)}
```
In fact, the parameter `+units=meters` does not work, and `+units=m` does:

```python
>>> import pyproj as pj
>>> srs = '+proj=merc +units=meters +a=6370000.0 +b=6370000.0 +lon_0=-74.9000015258789 +lat_ts=4.300000190734863 +nadgrids=@null'
>>> pj.Proj(srs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/pyproj/proj.py", line 146, in __init__
    self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
  File "/usr/lib/python3.8/site-packages/pyproj/crs/crs.py", line 437, in from_user_input
    return CRS(value)
  File "/usr/lib/python3.8/site-packages/pyproj/crs/crs.py", line 293, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2313, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: +proj=merc +units=meters +a=6370000.0 +b=6370000.0 +lon_0=-74.9000015258789 +lat_ts=4.300000190734863 +nadgrids=@null +type=crs: (Internal Proj Error: proj_create: Error -7 (unknown unit conversion id))

>>> pj.Proj(srs.replace('+units=meters', '+units=m'))
Proj('+proj=merc +lat_ts=4.30000019073486 +lon_0=-74.9000015258789 +x_0=0 +y_0=0 +R=6370000 +nadgrids=@null +units=m +no_defs', preserve_units=True)
```

**Comment by pgamez** [comment]
Therefore, I would propose, more or less, these kind of changes to file src/wrf/projection.py

```diff
diff --git a/src/wrf/projection.py b/src/wrf/projection.py
index 021b7f1..00d7b6f 100644
--- a/src/wrf/projection.py
+++ b/src/wrf/projection.py
@@ -532,6 +532,7 @@ class LambertConformal(WrfProj):
         _cf_params["longitude_of_central_meridian"] = self.stand_lon
         _cf_params["latitude_of_projection_origin"] = self.moad_cen_lat
         _cf_params["semi_major_axis"] = Constants.WRF_EARTH_RADIUS
+        _cf_params["semi_minor_axis"] = Constants.WRF_EARTH_RADIUS
 
         return _cf_params
 
@@ -602,7 +603,7 @@ class LambertConformal(WrfProj):
                     if _ismissing(self.truelat2)
                     else self.truelat2)
 
-        _proj4 = ("+proj=lcc +units=meters +a={} +b={} +lat_1={} "
+        _proj4 = ("+proj=lcc +units=m +a={} +b={} +lat_1={} "
                   "+lat_2={} +lat_0={} +lon_0={} +nadgrids=@null".format(
                       Constants.WRF_EARTH_RADIUS,
                       Constants.WRF_EARTH_RADIUS,
@@ -654,6 +655,8 @@ class Mercator(WrfProj):
         _cf_params["grid_mapping_name"] = "mercator"
         _cf_params["longitude_of_projection_origin"] = self.stand_lon
         _cf_params["standard_parallel"] = self.truelat1
+        _cf_params["semi_major_axis"] = Constants.WRF_EARTH_RADIUS
+        _cf_params["semi_minor_axis"] = Constants.WRF_EARTH_RADIUS
 
         return _cf_params
 
@@ -714,7 +717,7 @@ class Mercator(WrfProj):
 
     def _proj4(self):
 
-        _proj4 = ("+proj=merc +units=meters +a={} +b={} "
+        _proj4 = ("+proj=merc +units=m +a={} +b={} "
                   "+lon_0={} +lat_ts={} +nadgrids=@null".format(
                                             Constants.WRF_EARTH_RADIUS,
                                             Constants.WRF_EARTH_RADIUS,
@@ -762,6 +765,8 @@ class PolarStereographic(WrfProj):
                                                                self.stand_lon)
         _cf_params["standard_parallel"] = self.truelat1
         _cf_params["latitude_of_projection_origin"] = self._hemi
+        _cf_params["semi_major_axis"] = Constants.WRF_EARTH_RADIUS
+        _cf_params["semi_minor_axis"] = Constants.WRF_EARTH_RADIUS
 
         return _cf_params
 
@@ -821,7 +826,7 @@ class PolarStereographic(WrfProj):
         return _cartopy
 
     def _proj4(self):
-        _proj4 = ("+proj=stere +units=meters +a={} +b={} "
+        _proj4 = ("+proj=stere +units=m +a={} +b={} "
                   "+lat0={} +lon_0={} +lat_ts={} +nadgrids=@null".format(
                                             Constants.WRF_EARTH_RADIUS,
                                             Constants.WRF_EARTH_RADIUS,
@@ -864,6 +869,8 @@ class LatLon(WrfProj):
     def _cf_params(self):
         _cf_params = {}
         _cf_params["grid_mapping_name"] = "latitude_longitude"
+        _cf_params["semi_major_axis"] = Constants.WRF_EARTH_RADIUS
+        _cf_params["semi_minor_axis"] = Constants.WRF_EARTH_RADIUS
         return _cf_params
 
     def _pyngl(self, geobounds, **kwargs):
@@ -920,7 +927,7 @@ class LatLon(WrfProj):
                 [geobounds.bottom_left.lat, geobounds.top_right.lat])
 
     def _proj4(self):
-        _proj4 = ("+proj=eqc +units=meters +a={} +b={} "
+        _proj4 = ("+proj=eqc +units=m +a={} +b={} "
                   "+lon_0={} +nadgrids=@null".format(
                       Constants.WRF_EARTH_RADIUS,
                       Constants.WRF_EARTH_RADIUS,
@@ -1037,6 +1044,8 @@ class RotatedLatLon(WrfProj):
         _cf_params["grid_north_pole_latitude"] = self._bm_cart_pole_lat
         _cf_params["grid_north_pole_longitude"] = self.pole_lon
         _cf_params["north_pole_grid_longitude"] = self._bm_lon_0
+        _cf_params["semi_major_axis"] = Constants.WRF_EARTH_RADIUS
+        _cf_params["semi_minor_axis"] = Constants.WRF_EARTH_RADIUS
 
         return _cf_params
 
```

**Comment by pgamez** [comment]
In addition, if you skip the earth radius in the CF format, the projection will not be handled correctly by the proj4 library

```python
#!/usr/bin/env python3

from netCDF4 import Dataset
import wrf
import pyproj as pj
import numpy as np


filename = 'wrfout_d03_2020-03-19_12:00:00'

with Dataset(filename) as wrfin:
    proj_params = wrf.get_proj_params(wrfin)

proj = wrf.getproj(**proj_params)

cf = {}
for k, v in proj.cf().items():
    if isinstance(v, np.float32):
        v = float(v)
    cf[k] = v

print(pj.CRS.from_cf(cf).to_proj4())

cf.update({'earth_radius': wrf.constants.Constants.WRF_EARTH_RADIUS})
print(pj.CRS.from_cf(cf).to_proj4())
```

This is the output. Note in 1st case the ellipsoid is `+datum=WGS84`, whilst in 2nd case is the WRF sphere (`+R=6370000`):

```
+proj=merc +lat_ts=4.30000019073486 +lon_0=-74.9000015258789 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs
+proj=merc +lat_ts=4.30000019073486 +lon_0=-74.9000015258789 +x_0=0 +y_0=0 +R=6370000 +units=m +no_defs +type=crs
```
