### ISSUE TITLE
Error using "pip install wrf-python" 

### ISSUE THREAD

**Issue by ar1128** [NCAR/wrf-python#216]
Hi! I want to install wrf-python package on macOS without installing conda on my device. I tried using pip install wrf-python, and it gives the following error:

Collecting wrf-python
  Using cached wrf-python-1.3.4.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /Users/ar/.pyenv/versions/3.11.4/bin/python3.11: No module named pip
      Traceback (most recent call last):
        File "/Users/ar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/ar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gd/znfwvf3j21dfp8c6jsvz8g0m0000gn/T/pip-build-env-0ct35wnd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gd/znfwvf3j21dfp8c6jsvz8g0m0000gn/T/pip-build-env-0ct35wnd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/gd/znfwvf3j21dfp8c6jsvz8g0m0000gn/T/pip-build-env-0ct35wnd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/gd/znfwvf3j21dfp8c6jsvz8g0m0000gn/T/pip-build-env-0ct35wnd/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I am confused how to troubleshoot, I am new to wrf-python, and these are my currently installed packages:

affine          2.4.0
attrs           23.1.0
certifi         2023.5.7
cftime          1.6.2
click           8.1.4
click-plugins   1.1.1
cligj           0.7.2
contourpy       1.1.0
cycler          0.11.0
fonttools       4.42.0
kiwisolver      1.4.4
matplotlib      3.7.2
netCDF4         1.6.4
numpy           1.25.2
packaging       23.1
pandas          2.0.3
Pillow          10.0.0
pip             23.2.1
pyparsing       3.0.9
pyproj          3.6.0
python-dateutil 2.8.2
pytz            2023.3
rasterio        1.3.8
rioxarray       0.15.0
seaborn         0.12.2
setuptools      65.5.0
six             1.16.0
snuggs          1.4.7
tzdata          2023.3
xarray          2023.7.0

**Comment by ozsk** [comment]
Hi, I have the same problem. Could you write how did you solve this problem?

**Comment by ar1128** [comment]
> Hi, I have the same problem. Could you write how did you solve this problem?

I think I was able to install it using homebrew, let me know if you are unable to do it this way
