### ISSUE TITLE
WRF-Python Install - Mac M3

### ISSUE THREAD

**Issue by wreed1989** [NCAR/wrf-python#235]
Hello!

I'm wanting to set-up and run WRF on my M3 (if possible) and reading through the documentation it sounds like the easiest way to do this is via 'conda forge'. However, I'm running into an issue when I attempt to install the program (see below). 

Is the platform not quite suitable with an M3 chip or are there additional instructions that need to be done to ensure the package and its dependencies are installed appropriately? 

I appreciate the assistance!

###############################################################################################
(WRF-Python) Billiam@Williams-MacBook-Pro ~ % conda install -c conda-forge wrf-python
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - wrf-python

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
###############################################################################################

**Comment by erogluorhan** [comment]
Hi, thanks very much for reaching out! Currently, WRF-Python shouldn't have support for Apple's ARM-based chips (M1-3), but we'd like to look into this as soon as we can. I am assigning this to myself and will keep you updated.

**Comment by phalucy** [comment]
you can install via source code. I have successfully installed it.

**Comment by wreed1989** [comment]
Did you happen to create a workflow when you did that? I'm guessing not but if you did, I'd love to see it to help me install it.

**Comment by phalucy** [comment]
Sorry, I didn't. I just followed the steps showed in the online document using gfortran/gcc.

Only one issue should be aware. Although I successfully installed the wrf-python with openmpi option on my M3 macbook pro and most functions works fine , but it fails when I tried to use mpi functions. I'm not familiar with the options/compilers, but it maybe related to the M series chips (arm64) only allow mcmodel=small.

**Comment by erogluorhan** [comment]
@wreed1989 , please see [this](https://github.com/NCAR/wrf-python/issues/199#issuecomment-1949394544) from our team to get a working source-code build for yourself using our conda environment. If you encounter issues, we are here for help! 

FYI: We will be looking into creating a conda release for this soon so that you can install the package from conda-forge, too, in the future.

**Comment by wreed1989** [comment]
@erogluorhan Appreciate you sending that over. I'm a little unfamiliar with installing via source code so I'll likely have to wait until the conda-forge option is available - or until I can track down additional instructions on how to install via source code. 

I'm looking forward to the conda-forge release!

**Comment by wreed1989** [comment]
Please let me know when it's ready to roll out! I appreciate it!

**Comment by lppezzi** [comment]
@erogluorhan 
Hi, I am also working in Apple M3 Max, and installed (via conda, from source) wrf_python.
However it is not working. Apparently there is an issue with netcdf4 (which was installed).
Please see the error below: 
Traceback (most recent call last):
  File "precipitacao_acumulada.py", line 8, in <module>
    from netCDF4 import Dataset
ModuleNotFoundError: No module named 'netCDF4'

any suggestion?
Cheers,

**Comment by DWesl** [comment]
> ```pycon
> Traceback (most recent call last):
>   File "precipitacao_acumulada.py", line 8, in <module>
>     from netCDF4 import Dataset 
> ModuleNotFoundError: No module named 'netCDF4'
> ```

This looks like an issue with either conda or netCDF4, but comparing `pip freeze` with `conda list` might indicate some directions for future inquiries, as might the output of `python -vddd precipitacao_acumulada.py`.

Destroying and re-creating the environment used to run this might also allow the script to run (or just creating an environment for this script).  There's no obvious reason the netCDF4 import would fail, so this kind of solution is one of the more likely to fix whatever the problem is and rules out a class of problems if it doesn't.

As a tip for future reports, surrounding your code or logs with triple backticks will preserve indentation better:
````markdown
```
Traceback:
   from netCDF4 import Dataset
ModuleNotFoundError
```
````

**Comment by HathewayWill** [comment]
> @wreed1989 , please see [this](https://github.com/NCAR/wrf-python/issues/199#issuecomment-1949394544) from our team to get a working source-code build for yourself. If you encounter issues, we are here for help!
> 
> FYI: We will be looking into creating a conda release for this soon so that you can install the package from conda-forge, too, in the future.

I have gotten it to work on Conda with a specific yaml file, I can share this.

Also @wreed1989 is WRF-python going to be updated anytime soon?

**Comment by erogluorhan** [comment]
Hi @wreed1989 , as per `[this update](https://github.com/NCAR/wrf-python/issues/199#issuecomment-1949394544)`, I think we can look into a release soon.

**Comment by cerodell** [comment]
Is there any update on when wrf-python will work on the Mac M chips?

**Comment by blutjens** [comment]
Are there any updates on this? It sounded like wrf-python is available on conda-forge, but I am on an M3 Max and running `conda install wrf-python -c conda-forge` is returning a PackagesNotFoundError error: The following packages are not available from current channels.

**Comment by phalucy** [comment]
The following steps works for me (on Macbook Pro with M3 Max):
```
git clone https://github.com/NCAR/wrf-python.git ./wrf-python
pip install build
python -c "import setuptools; setuptools.setup()" sdist
python -m build --sdist --wheel
pip install numpy==1.26.4
```
However, even if I previously compiled the omp-related programs, the omp functions does not work properly.
But, it is still great to have it being functional on Apple Silicons.

**Comment by FelixLangot** [comment]
Hi all, had the same issue for some time but in late 2025 someone published a temporary solution in this thread which helped me:
https://forum.mmm.ucar.edu/threads/cannot-use-the-wrf-getvar.24078/
If you scroll down the thread a bit at some point there is a .pdf that is shared and everything is explained on there.

**Comment by kafitzgerald** [comment]
WRF-Python should now be available on conda-forge for osx-arm64 (i.e. Apple silicon / M-series chips):

`conda install wrf-python`

Feel free to reopen if you have any related issues or open a new one if you run into anything else.
