### ISSUE TITLE
xarray became a hard dependency

### ISSUE THREAD

**Issue by letmaik** [NCAR/wrf-python#59]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python36\lib\site-packages\wrf\__init__.py", line 16, in <module>
    from . import api
  File "C:\Python36\lib\site-packages\wrf\api.py", line 11, in <module>
    from .routines import getvar
  File "C:\Python36\lib\site-packages\wrf\routines.py", line 11, in <module>
    from .g_latlon import get_lat, get_lon
  File "C:\Python36\lib\site-packages\wrf\g_latlon.py", line 6, in <module>
    from xarray import DataArray
ModuleNotFoundError: No module named 'xarray'
Command exited with code 1
```

**Comment by bladwig1** [comment]
xarray shouldn't be a required dependency. This is a bug.
