### ISSUE TITLE
Update PyPI from 1.3.1

### ISSUE THREAD

**Issue by jsheedy** [NCAR/wrf-python#93]
The latest version of wrf-python on [PyPI](https://pypi.org/project/wrf-python/) is 1.3.1 though several [releases](https://github.com/NCAR/wrf-python/releases) exist since then. My installation in a clean virtualenv is failing due to lack of numpy in setup and later releases have [a fix to bootstrap numpy](https://github.com/NCAR/wrf-python/commit/53b08c40dc9adec5214c745ffa8453e78a652135#diff-2eeaed663bd0d25b7e608891384b7298). 

Updating PyPI will resolve this issue.

**Comment by yriveiro** [comment]
I'm hitting this bug also,

```sh
#18 48.39 Collecting wrf-python<2.0.0,>=1.3.1
#18 48.41   Downloading wrf-python-1.3.1.tar.gz (1.1 MB)
#18 48.63     ERROR: Command errored out with exit status 1:
#18 48.63      command: /usr/sbin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-omhdtztw/wrf-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-omhdtztw/wrf-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k6t63ke8
#18 48.63          cwd: /tmp/pip-install-omhdtztw/wrf-python/
#18 48.63     Complete output (5 lines):
#18 48.63     Traceback (most recent call last):
#18 48.63       File "<string>", line 1, in <module>
#18 48.63       File "/tmp/pip-install-omhdtztw/wrf-python/setup.py", line 7, in <module>
#18 48.63         import numpy.distutils.core
#18 48.63     ModuleNotFoundError: No module named 'numpy'
```

**Comment by michaelavs** [comment]
@yriveiro we are currently looking into this issue. We would like to know if you are able to use [conda forge](https://wrf-python.readthedocs.io/en/latest/installation.html) to install the wrf-python package? The version currently being run under the `conda forge` route is 1.3 so you should be able to resolve the issue you were having through this route. We are also discussing removing the PyPI installation method in favor of the conda forge method, so please let me know if conda forge will be an issue so we can take that into consideration when we make that decision.

Overall, we have found that there was a hold up on the the conda feedstock for this repository and are working to gain access to the feedstock repo which would allow us to use the most recent wrf-python version in conda forge.

**Comment by yriveiro** [comment]
Running Conda for me is not desirable in my use case because I run wrf-python inside a container and Conda is not very container friendly in terms of image size.

Removing support for PyPI means that wrf-python has a hard dependency on Conda. You will wipe out the support to use wrf-python as a vanilla package in a simple container with 200MB size or do a simple pip install and use it in a ipyhton environment.

**Comment by michaelavs** [comment]
@yriveiro Thank you for your quick response and input! Another option outside of using conda forge is git cloning the wrf-python repository and installing from there with `pip install .`, would this work in your situation?

**Comment by hanschen** [comment]
Just wanted to chime in and say that I also prefer to install wrf-python from PyPI because I can easily include it in `requirements.txt` and install all required packages with `pip install -r requirements.txt`, for example in virtual environments.

If PyPI is not an alternative, I could of course just specify the GitHub repository instead, e.g. `git+https://github.com/NCAR/wrf-python@1.3.2.6#egg=wrf-python`.

It's worth noting that the 1.3.1 version on PyPI doesn't work in newer Python versions (3.8+) due to the move of `Iterable` etc. to `collections.abc`.

**Comment by mmuraro** [comment]
Good morning, I have the same problem as yriveiro. I would like to know if there is any news regarding the solution to this bug.
A thousand thanks
